name: summarizer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.3.1
  - fastapi=0.100.0
  - gunicorn=23.0.0
  - uvicorn=0.23.1
  - pytest=7.4.0
  - httpx=0.24.1
  - python-multipart=0.0.12
  - nltk=3.9.1
  - numpy=1.24.3
  - scipy=1.11.3
  - scikit-learn=1.3.0
  - beautifulsoup4=4.12.3
  - dask=2023.5.0
  - distributed=2023.5.0
  - dask-ml=2023.3.24
  - pandas=2.0.3
  - aiohttp=3.9.1
  - pydantic-settings=2.1.0
  - pip:
    - tiktoken==0.7.0
    - EbookLib==0.18
    - chardet==5.2.0
    - pytest-xdist
    - pytest-asyncio
